### ISSUE TITLE
meaning of non-zero elements in tracksFeatIndxCG

### ISSUE THREAD

**Issue by Blosberg** [mcianfrocco/Matlab#1]
Thanks very much for providing this software. 
After reading the associated documentation (version 2.1.1), I am still unclear about the meaning of the variable `tracksFeatIndxCG` that is produced within the tracksFinal data structure. The number of rows and columns (`# subtracks` x `# frames` ) is quite clear, as is the implication of a zero value for non-existent tracks. 
When the value is **non-zero**, however, it's not clear to me what a "connectivity matrix" element value would imply in this context. (The direct quote from the doc is "Connectivity matrix of particles between frames, after gap closing")

So, suppose for example that in compound track `i`, for sub-track `j`, and at the frame `k` in the movie, we have `tracksFinal(i).tracksFeatIndexCG(j,k) = M`, where `M` is a non-zero value (say, 7, for example). What does this value imply? Can you elaborate on what sense of "connectivity" a value of 7 would imply here? Thank you for your time.

**Comment by mcianfrocco** [comment]
Hi @Blosberg - thanks for posting a question. TBH I haven't looked at this in over 5 years, so I'm not sure I'm up to speed in order to answer your question. Sorry! If you do find out anything, please be sure to post it here.
